/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programaritmatikadinamis;

/**
 *
 * @author Fariz
 */
public class ProgramAritmatikaDinamisForm extends javax.swing.JFrame {
    String jns = "";
    int jml;
    

    /**
     * Creates new form ProgramAritmatikaDinamisForm
     */
    public ProgramAritmatikaDinamisForm() {
        initComponents();
        
        jns = null;
        
        jLabel3.setVisible(false);
        cbJumlah.setVisible(false);
        labelbilangan1.setVisible(false);
        labelbilangan2.setVisible(false);
        tb2.setVisible(false);
        tb1.setVisible(false);
        labelbilangan3.setVisible(false);
        labelbilangan4.setVisible(false);
        tb4.setVisible(false);
        tb3.setVisible(false);
        bHitung.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbJumlah = new javax.swing.JComboBox<>();
        labelbilangan1 = new javax.swing.JLabel();
        tb1 = new javax.swing.JTextField();
        tb2 = new javax.swing.JTextField();
        labelbilangan2 = new javax.swing.JLabel();
        tb3 = new javax.swing.JTextField();
        labelbilangan3 = new javax.swing.JLabel();
        labelbilangan4 = new javax.swing.JLabel();
        tb4 = new javax.swing.JTextField();
        labelhasil = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareahasil = new javax.swing.JTextArea();
        bHitung = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        bTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 18)); // NOI18N
        jLabel1.setText("Program Aritmatika");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 170, 30);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setForeground(new java.awt.Color(204, 204, 204));
        panel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Jumlah Bilangan");
        panel.add(jLabel3);
        jLabel3.setBounds(10, 70, 110, 30);

        cbJumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        cbJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJumlahActionPerformed(evt);
            }
        });
        panel.add(cbJumlah);
        cbJumlah.setBounds(220, 70, 150, 30);

        labelbilangan1.setText("Bilangan 1");
        panel.add(labelbilangan1);
        labelbilangan1.setBounds(20, 120, 90, 30);
        panel.add(tb1);
        tb1.setBounds(220, 120, 120, 30);
        panel.add(tb2);
        tb2.setBounds(220, 160, 120, 30);

        labelbilangan2.setText("Bilangan 2");
        panel.add(labelbilangan2);
        labelbilangan2.setBounds(20, 160, 90, 30);
        panel.add(tb3);
        tb3.setBounds(220, 200, 120, 30);

        labelbilangan3.setText("Bilangan 3");
        panel.add(labelbilangan3);
        labelbilangan3.setBounds(20, 200, 90, 30);

        labelbilangan4.setText("Bilangan 4");
        panel.add(labelbilangan4);
        labelbilangan4.setBounds(20, 240, 90, 30);
        panel.add(tb4);
        tb4.setBounds(220, 240, 120, 30);

        labelhasil.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelhasil.setText("Hasil");
        panel.add(labelhasil);
        labelhasil.setBounds(20, 350, 70, 20);

        textareahasil.setEditable(false);
        textareahasil.setColumns(20);
        textareahasil.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        textareahasil.setRows(5);
        jScrollPane1.setViewportView(textareahasil);

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(90, 350, 260, 100);

        bHitung.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });
        panel.add(bHitung);
        bHitung.setBounds(220, 290, 120, 30);

        jPanel2.setLayout(null);

        ket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(ket);
        ket.setBounds(10, 0, 150, 40);

        panel.add(jPanel2);
        jPanel2.setBounds(120, 20, 170, 40);

        getContentPane().add(panel);
        panel.setBounds(30, 90, 390, 470);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 100, 20);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        cbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisActionPerformed(evt);
            }
        });
        getContentPane().add(cbJenis);
        cbJenis.setBounds(250, 50, 140, 30);

        bTutup.setText("Tutup");
        bTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTutupActionPerformed(evt);
            }
        });
        getContentPane().add(bTutup);
        bTutup.setBounds(320, 570, 90, 30);

        setSize(new java.awt.Dimension(456, 645));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1, a2, a3, a4;
        
        a1 = Double.parseDouble(tb1.getText().toString());
        a2 = Double.parseDouble(tb2.getText().toString());
        
        
        if(jns.equals("Penjumlahan")) {
            if(jml == 2) {
                hsl = a1 + a2;
                
                textareahasil.setText(""+a1+ " + " + a2 + " = " + hsl);
            }
            if(jml == 3) {                
                a3 = Double.parseDouble(tb3.getText().toString());
                hsl = a1 + a2 + a3;
                
                textareahasil.setText("" + a1 + " + " + a2 + " + " + a3 + " = " + hsl);
            }
            if(jml == 4) {                               
                a3 = Double.parseDouble(tb3.getText().toString());
                a4 = Double.parseDouble(tb4.getText().toString());
                
                hsl = a1 + a2 + a3 + a4;
                textareahasil.setText("" + a1 + " + " + a2 + " + " + a3 + " + " + a4 + " = " + hsl);
            }
        }
        if(jns.equals("Perkalian")) {
            if(jml == 2) {
                hsl = a1 * a2;
                
                textareahasil.setText(""+a1+ " x " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(tb3.getText().toString());
                hsl = a1 * a2 * a3;
                textareahasil.setText("" + a1 + " x " + a2 + " x " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(tb3.getText().toString());
                a4 = Double.parseDouble(tb4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                textareahasil.setText("" + a1 + " + " + a2 + " + " + a3 + " + " + a4 + " = " + hsl);
            }
        }
        if(jns.equals("Pembagian")) {
            if(jml == 2) {
                hsl = a1 / a2;
                
                textareahasil.setText(""+a1+ " : " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(tb3.getText().toString());
                hsl = a1 / a2 / a3;
                textareahasil.setText("" + a1 + " : " + a2 + " : " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(tb3.getText().toString());
                a4 = Double.parseDouble(tb4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                textareahasil.setText("" + a1 + " : " + a2 + " : " + a3 + " : " + a4 + " = " + hsl);
            }
        }
        if(jns.equals("Pengurangan")) {
            if(jml == 2) {
                hsl = a1 - a2;
                
                textareahasil.setText(""+a1+ " - " + a2 + " = " + hsl);
            }
            if(jml == 3) {
                a3 = Double.parseDouble(tb3.getText().toString());
                hsl = a1 - a2 - a3;
                textareahasil.setText("" + a1 + " - " + a2 + " - " + a3 + " = " + hsl);
            }
            if(jml == 4) {
                a3 = Double.parseDouble(tb3.getText().toString());
                a4 = Double.parseDouble(tb4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                textareahasil.setText("" + a1 + " - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }
        }
        
    }//GEN-LAST:event_bHitungActionPerformed

    private void bTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bTutupActionPerformed

    private void cbJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJumlahActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_cbJumlahActionPerformed

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_cbJenisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatikaDinamisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatikaDinamisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatikaDinamisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatikaDinamisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatikaDinamisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bTutup;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbJumlah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel labelbilangan1;
    private javax.swing.JLabel labelbilangan2;
    private javax.swing.JLabel labelbilangan3;
    private javax.swing.JLabel labelbilangan4;
    private javax.swing.JLabel labelhasil;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField tb1;
    private javax.swing.JTextField tb2;
    private javax.swing.JTextField tb3;
    private javax.swing.JTextField tb4;
    private javax.swing.JTextArea textareahasil;
    // End of variables declaration//GEN-END:variables

    public void setJenis() {
        if(cbJenis.getSelectedItem().equals("Penjumlahan")) {
            jns = "Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            cbJumlah.setEnabled(true);
            jLabel3.setVisible(true);
            cbJumlah.setVisible(true);
            bHitung.setVisible(true);
        }
        else if(cbJenis.getSelectedItem().equals("Pengurangan")) {
            jns = "Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            cbJumlah.setEnabled(true);
            jLabel3.setVisible(true);
            cbJumlah.setVisible(true);
            bHitung.setVisible(true);
        }
        else
        if(cbJenis.getSelectedItem().equals("Perkalian")) {
            jns = "Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            cbJumlah.setEnabled(true);
            jLabel3.setVisible(true);
            cbJumlah.setVisible(true);
            bHitung.setVisible(true);
        }
        else
        if(cbJenis.getSelectedItem().equals("Pembagian")) {
            jns = "Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            cbJumlah.setEnabled(true);
            jLabel3.setVisible(true);
            cbJumlah.setVisible(true);
            bHitung.setVisible(true);
        }
    }

    public void getJumlah() {
        if(cbJumlah.getSelectedItem().equals("2")){
           labelbilangan1.setVisible(true);
           labelbilangan2.setVisible(true);
           tb2.setVisible(true);
           tb1.setVisible(true);
           labelbilangan3.setVisible(false);
           tb3.setVisible(false);
           
           labelbilangan4.setVisible(false);
           tb4.setVisible(false);
           
           jml = 2;
        }
        else
        if(cbJumlah.getSelectedItem().equals("3")){
           labelbilangan1.setVisible(true);
           labelbilangan2.setVisible(true);
           tb2.setVisible(true);
           tb1.setVisible(true);
           tb3.setVisible(true);
           labelbilangan3.setVisible(true);
            
            labelbilangan4.setVisible(false);
            tb4.setVisible(false);
            
            jml=3;
        }
        else
        if(cbJumlah.getSelectedItem().equals("4")){
           labelbilangan1.setVisible(true);
           labelbilangan2.setVisible(true);
           tb2.setVisible(true);
           tb1.setVisible(true);
           tb3.setVisible(true);
           labelbilangan3.setVisible(true);
            
           labelbilangan4.setVisible(true);
           tb4.setVisible(true);
            
            jml=4;
        }
    }
}

